project_id = "wiisixdctrokfmhnrxnw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329

[realtime]
enabled = true
hostname = "localhost"
port = 54323

[studio]
enabled = true
port = 54324
hostname = "localhost"

[inbucket]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[storage]
enabled = true
port = 54327

[functions]
enabled = true
port = 54328

[functions.send-email]
verify_jwt = true